using System;
using System.Collections.Generic;

namespace BigData.Models
{
    public partial class CdAssemblyCompT
    {
        public string WellId { get; set; }
        public string WellboreId { get; set; }
        public string AssemblyId { get; set; }
        public string AssemblyCompId { get; set; }
        public string SectTypeCode { get; set; }
        public string IsFlowOut { get; set; }
        public string CsgCompGroupCode { get; set; }
        public string SubAssemblyId { get; set; }
        public string SubAssemblyCompId { get; set; }
        public string PropConnectCatalogId { get; set; }
        public string PropConnectCatalogItemId { get; set; }
        public string MaterialId { get; set; }
        public string GradeId { get; set; }
        public double? AnisotropicHoop { get; set; }
        public double? AnisotropicRadial { get; set; }
        public double? AxialRating { get; set; }
        public double? BotConnLength { get; set; }
        public double? AverageJointLength { get; set; }
        public double? BotConnOd { get; set; }
        public double? AreaOpeningInternal { get; set; }
        public string BotConnType { get; set; }
        public string BoxPinConfig { get; set; }
        public double? ClosedEndDisplacement { get; set; }
        public string CatalogId { get; set; }
        public double? Centers { get; set; }
        public string CatalogItemId { get; set; }
        public double? CompCost { get; set; }
        public string CatalogKeyDesc { get; set; }
        public double? IdDrift { get; set; }
        public string CompGroup { get; set; }
        public double? FishneckLength { get; set; }
        public string ConnectionType { get; set; }
        public double? CorrectionFactor { get; set; }
        public string ConnectionGrade { get; set; }
        public string ConnectionName { get; set; }
        public double? Conductivity { get; set; }
        public string Condition { get; set; }
        public double? DistanceFromBit { get; set; }
        public string CompName { get; set; }
        public double? FishneckOd { get; set; }
        public double? CostPerLength { get; set; }
        public double? FatigueEnduranceLimit { get; set; }
        public double? FrictionCoeff { get; set; }
        public double? Density { get; set; }
        public string Grade { get; set; }
        public double? IdMin { get; set; }
        public string IsThreadlockUsed { get; set; }
        public string Description { get; set; }
        public double? Displacement { get; set; }
        public double? Length { get; set; }
        public double? IdBody { get; set; }
        public double? LinearCapacity { get; set; }
        public double? IdConnection { get; set; }
        public string Material { get; set; }
        public double? IdCoupling { get; set; }
        public string IsBitFlow { get; set; }
        public double? JointStrength { get; set; }
        public short? Joints { get; set; }
        public string IsSpiral { get; set; }
        public string Manufacturer { get; set; }
        public double? MdBase { get; set; }
        public string IsPortOpen { get; set; }
        public double? MdTop { get; set; }
        public string Model { get; set; }
        public double? LengthInsideCoupling { get; set; }
        public string NominalSize { get; set; }
        public double? LengthOutsideCoupling { get; set; }
        public double? OdMax { get; set; }
        public string ManufacturerId { get; set; }
        public double? LengthToolJoint { get; set; }
        public string PipeType { get; set; }
        public double? MakeupTorque { get; set; }
        public double? LengthToolJointInside { get; set; }
        public double? PlainEndCost { get; set; }
        public double? PoissonsRatio { get; set; }
        public string Remarks { get; set; }
        public double? MinYieldStress { get; set; }
        public string SerialNo { get; set; }
        public string ServiceType { get; set; }
        public string NominalWeight { get; set; }
        public string Supplier { get; set; }
        public double? TopConnLength { get; set; }
        public double? TopConnOd { get; set; }
        public string TopConnType { get; set; }
        public double? OdBody { get; set; }
        public short? NumRows { get; set; }
        public double? TorqueMax { get; set; }
        public double? OdConnection { get; set; }
        public double? TorqueMin { get; set; }
        public double? ThermalExpansionCoef { get; set; }
        public string ThreadType { get; set; }
        public double? UltimateTensileStrength { get; set; }
        public double? WallThickness { get; set; }
        public double? PressureBurst { get; set; }
        public double? ApproximateWeight { get; set; }
        public double? PressureCollapse { get; set; }
        public double? YieldWeightBody { get; set; }
        public double? YieldWeightConn { get; set; }
        public double? YoungsModulus { get; set; }
        public string ServiceClass { get; set; }
        public int? SequenceNo { get; set; }
        public double? UndercutAngle { get; set; }
        public double? WallThicknessPercent { get; set; }
        public double? AnnularFlowArea { get; set; }
        public double? BitflowRate { get; set; }
        public string Range { get; set; }
        public double? Width { get; set; }
        public double? BladeLength { get; set; }
        public double? ContactLength { get; set; }
        public double? ConnectionTorsionalYield { get; set; }
        public string CoringMode { get; set; }
        public string CompTypeCode { get; set; }
        public double? MaxHoleSize { get; set; }
        public double? MaxRecFlowRate { get; set; }
        public double? MaxSealPressure { get; set; }
        public double? PercentPlugged { get; set; }
        public double? MinOpPressure { get; set; }
        public double? NumberSlots { get; set; }
        public double? IdSleeve { get; set; }
        public double? OdAverage { get; set; }
        public double? OdExtended { get; set; }
        public double? OdRetracted { get; set; }
        public double? Tfa { get; set; }
        public double? OdSleeve { get; set; }
        public double? PilotHoleSize { get; set; }
        public double? ScreenLength { get; set; }
        public double? SleeveLength { get; set; }
        public double? SlotWidth { get; set; }
        public double? PercAreaOpen { get; set; }
        public double? FloatId { get; set; }
        public string PipeRunId { get; set; }
        public string PipeDataId { get; set; }
        public string EventId { get; set; }
        public string IsSlotted { get; set; }
        public double? SlotTopMd { get; set; }
        public double? SlotBottomMd { get; set; }
        public string SlotType { get; set; }
        public double? SlotLength { get; set; }
        public double? PerfHoleDiameter { get; set; }
        public double? PerfDensity { get; set; }
        public string IsSlotRound { get; set; }
        public string MaterialNum { get; set; }
        public string InternalRef { get; set; }
        public double? PressRatingTop { get; set; }
        public double? PressRatingBot { get; set; }
        public double? WlBoreSize { get; set; }
        public string FishNeckType { get; set; }
        public string ProfileType { get; set; }
        public string PocketType { get; set; }
        public double? PocketSize { get; set; }
        public string Coating { get; set; }
        public string ExternalCompAccId { get; set; }
        public double? InternalPressureTest { get; set; }
        public double? ExternalPressureTest { get; set; }
        public double? HangerSize { get; set; }
        public double? WorkingPress { get; set; }
        public double? MinId { get; set; }
        public double? MinSlipOd { get; set; }
        public double? MaxSlipOd { get; set; }
        public double? SlipTaperAngle { get; set; }
        public double? SlipLength { get; set; }
        public double? SlipFrictionFactor { get; set; }
        public double? SafetyFactor { get; set; }
        public double? NominalWeightMeasure { get; set; }
        public double? CriticalPercentCollapse { get; set; }
        public double? CriticalPercentAxial { get; set; }
        public double? CriticalPercentTriaxial { get; set; }
        public double? CriticalPercentTriaxialHoop { get; set; }
        public string SealType { get; set; }
        public double? JointStrengthCompression { get; set; }
        public double? JointCost { get; set; }
        public double? PipePressureBurst { get; set; }
        public double? MaxBend { get; set; }
        public string CreateUserId { get; set; }
        public string CreateAppId { get; set; }
        public DateTime? CreateDate { get; set; }
        public string UpdateUserId { get; set; }
        public string UpdateAppId { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string AuditRemarks { get; set; }
        public string CatalogName { get; set; }
        public string IsUserDefined { get; set; }

        public virtual CdAssemblyT CdAssemblyT { get; set; }
        public virtual CdBhaCompBitT CdBhaCompBitT { get; set; }
    }
}
